name: Demo Workflow 2
on: 
    push:
        branches:
            - main
            #update on main to test on branch
jobs:
 Demo-Job:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v4
     - name: List files in the repository
       run: |
         echo "Listing files in the repository(${{ github.workspace }}).."
         ls ${{ github.workspace }}
     - run: echo "Job's status is ${{ job.status }}"
     - name: read the README.md file
       run: cat ${{ github.workspace }}/README.md
       # can also type cat README.md
