name: GitHub Actions Secrets
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 This secret is pulled from $ {{ secrets.SECRET_HOST}}"